# Base configs
baseurl: "https://b43e6b755e20353d341b45cb7ea68742.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio -kiramisu"
subtitle: "See the world through my eyes!"
author: "overheadocean"
header:
 title: "portfolio"
 subtitle: "by kiramisu"
footer:
 name: "kiramisu"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.google.com"
  twitter: "https://www.google.com"
  instagram: "https://www.google.com"
  dribbble: "https://www.google.com"
  linkedin: "https://www.google.com"
  github: "https://www.google.com"
